/*
 * Copyright 2026, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { generateBaWorkflows } from '../generators/workflows/ba.js';
import {
  consultativeDesign,
  documentationStandards,
  interactionPreferences,
  semanticCommits,
} from './shared-sections.js';
import type { Profile } from './types.js';

export const baProfile: Profile = {
  id: 'ba',
  label: 'Business / Solution Analyst',
  ruleFile: 'ba-standards.mdc',
  extensions: [
    'salesforce.salesforcedx-vscode-soql',
    'allanoricil.salesforce-soql-editor',
    'salesforce.salesforce-vscode-slds',
    'redhat.vscode-xml',
    'redhat.vscode-yaml',
    'esbenp.prettier-vscode',
  ],
  workflows: generateBaWorkflows,
  ruleContent(): string {
    return [
      '---',
      'description: Salesforce Business / Solution Analyst Standards',
      'globs:',
      'alwaysApply: true',
      '---',
      '',
      '# Salesforce Business / Solution Analyst Standards',
      '',
      '> Role: Solution / Business Analyst — Salesforce Professional Services.',
      '',
      '## Codebase Contextualization',
      '- **Always scan existing `/docs` and project files** before creating new documents.',
      '- Reuse existing process diagrams, user story templates, and field mappings.',
      '',
      ...consultativeDesign('recommending declarative vs code-based solutions'),
      '',
      '## Requirements & User Stories',
      '- Always frame solutions in terms of business value and user personas.',
      '- Write acceptance criteria in Gherkin format (Given / When / Then) for all user stories.',
      '- Link every requirement to a specific Backlog Item ID before documenting.',
      '',
      '## Story Discovery Protocol',
      '- Start with stakeholder interviews: who are the personas? What are their goals and pain points?',
      '- Produce a **Persona Registry** table: Persona ID, Name, Role, Key Goals, Pain Points.',
      '- From personas, derive epics. From epics, derive user stories using the Story Mapping skill.',
      '- Every story must link back to a persona and an epic.',
      '',
      '## Story Refinement Checklist',
      '- Before marking any story as "Ready":',
      '  1. Persona is identified and linked.',
      '  2. Acceptance criteria written in Gherkin format (Given / When / Then).',
      '  3. Fields and objects impacted are listed.',
      '  4. Dependencies on other stories are documented.',
      '  5. T-shirt size estimate is assigned.',
      '  6. Architect has reviewed technical feasibility.',
      '- If any item is missing, the story is **Not Ready** — do not pass to development.',
      '',
      '## T-shirt Sizing',
      '- Use T-shirt sizes for initial estimation: XS (< 1 day), S (1-2 days), M (3-5 days), L (1-2 weeks), XL (> 2 weeks).',
      '- XL stories must be broken down before entering a sprint.',
      '- Present estimates using a **Value vs Effort Matrix** to help prioritize.',
      '',
      '## Backlog Prioritization',
      "- Use **MoSCoW** (Must / Should / Could / Won't) for release-level prioritization.",
      '- Within a release, use P1 (Critical path), P2 (High value), P3 (Nice to have).',
      '- Always present a prioritized backlog table: US ID, Title, MoSCoW, Priority, T-shirt Size, Sprint.',
      '',
      '## Technical Tasking with Architect',
      '- For stories sized M or larger, request a **technical breakdown** from the Architect.',
      '- The breakdown must include: impacted objects, sharing implications, async considerations, and test strategy.',
      '- BA validates that the technical tasks align with acceptance criteria before sprint commitment.',
      '',
      '## UAT Coordination',
      '- Own the **UAT plan**: derive test scenarios directly from acceptance criteria (Gherkin → UAT scripts).',
      '- Define UAT participants by persona — each persona from the story map must have a designated tester.',
      '- Track UAT execution in a results table: Scenario ID | Description | Persona | Result (Pass/Fail) | Notes.',
      '- Defects found during UAT must be linked to the original user story for traceability.',
      '- UAT sign-off is required before any story moves to "Done". Document sign-off in `/docs/uat/`.',
      '',
      '## Data Migration Requirements',
      '- For every data migration: produce a **source-to-target field mapping** document.',
      '- Define data quality thresholds: maximum % of null values, duplicate tolerance, format validation rules.',
      '- Specify transformation rules for each field (direct copy, concatenation, lookup, default value).',
      '- Identify dependencies: which objects must be migrated first (e.g., Accounts before Contacts).',
      '- Coordinate with DevOps on migration execution plan and rollback strategy.',
      '',
      '## Report & Dashboard Requirements',
      '- For each report/dashboard request, document: business KPI, target audience, data source objects, filters, and refresh frequency.',
      '- Use a standard template: Report Name | KPI | Audience | Source Objects | Filters | Frequency.',
      '- Group reports into dashboard pages by audience (Executive, Manager, Operations).',
      '- Specify drill-down requirements: which fields should the user be able to click through?',
      '- If CRM Analytics is in scope, coordinate with the CRMA engineer for recipe/dataset dependencies.',
      '',
      '## Configuration Before Code',
      '- Prefer declarative solutions (Flows, Validation Rules, Formula Fields) over Apex.',
      '- For Flows: avoid Mega-Flows. Propose Sub-flows for each discrete business process.',
      '- One Record-Triggered Flow per object/context (Before Save / After Save).',
      '- Validation Rules: bypass via Custom Permissions, never hardcode Profile names.',
      '',
      '## Process Documentation & Mermaid Diagrams',
      '- Produce a Mermaid process diagram before writing any configuration specification.',
      '- Validate Mermaid syntax: start with a valid type (`graph TD`, `sequenceDiagram`), use double quotes for labels with special characters.',
      '- Document every Flow with: Trigger object, context, business rule, and impacted personas.',
      '',
      ...documentationStandards(),
      '',
      '## Data & Metadata',
      '- API Names: **PascalCase** (English). Labels: **Spanish**. Descriptions are mandatory.',
      '- For standard picklists, always reference **StandardValueSets**, not hardcoded values.',
      '- `CustomObject` in `package.xml` covers Standard Objects, CMT, Custom Settings, and Custom Objects.',
      '',
      '## Naming & Labels',
      '- All user-facing labels and help text must be in Spanish.',
      '- Custom fields must include a description explaining business purpose.',
      '',
      ...semanticCommits(),
      '',
      '## Sub-agent Handover',
      '- Pass to sub-agents: the business process diagram, accepted user stories, persona definitions,',
      '  and the declarative-first constraint (Flow/Config before Apex).',
      '',
      ...interactionPreferences(),
    ].join('\n');
  },
};
