/*
 * Copyright 2026, Jaime Terrats.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { generateDeveloperWorkflows } from '../generators/workflows/developer.js';
import {
  consultativeDesign,
  deployment,
  documentationStandards,
  interactionPreferences,
  semanticCommits,
} from './shared-sections.js';
import type { Profile } from './types.js';

export const developerProfile: Profile = {
  id: 'developer',
  label: 'Developer',
  ruleFile: 'developer-standards.mdc',
  extensions: [
    'salesforce.salesforcedx-vscode-apex-debugger',
    'salesforce.salesforcedx-vscode-apex-replay-debugger',
    'salesforce.sfdx-code-analyzer-vscode',
    'chuckjonas.apex-pmd',
    'chuckjonas.salesforce-diff',
    'omniphx.sfdx-auto-deployer',
    'hugoom.sfdx-autoheader',
    'vignaeshrama.sfdx-package-xml-generator',
    'financialforce.lana',
  ],
  workflows: generateDeveloperWorkflows,
  ruleContent(): string {
    return [
      '---',
      'description: Salesforce Developer Standards',
      'globs:',
      'alwaysApply: true',
      '---',
      '',
      '# Salesforce Developer Standards',
      '',
      '> Role: Salesforce Developer — Salesforce Professional Services.',
      '',
      ...consultativeDesign(),
      '',
      '## Code Generation',
      '- Always read `sfdx-project.json` → `sourceApiVersion` before generating any Apex, LWC, or metadata.',
      '- Infer naming patterns from the existing project. `JT_` is a framework prefix — preserve as-is.',
      '- Test classes: `<ClassName>_Test`. Trigger handlers: `<ObjectName>TriggerHandler`.',
      '',
      '## Apex Rules',
      '- Default: `with sharing` on all Apex classes.',
      '- Exception: Apex REST (`@RestResource`) classes → always `without sharing`.',
      '- **No SOQL or DML inside loops.** Collect, then query/DML once outside.',
      "- One trigger per object. Zero logic in triggers — delegate entirely to Kevin O'Hara Trigger Handler.",
      '- Scan for existing custom exception class before writing `try-catch`. If none exists, propose one.',
      '',
      '## Data Layer',
      '- Propose **JT_DynamicQueries** first. Fallback: **DataSelector** (`inherited sharing`).',
      '- If strategy is unclear, ask: *"¿Usamos JT_DynamicQueries o DataSelector?"*.',
      '- Always bulkify: handle 1 to N records.',
      '',
      '## LWC',
      '- Prioritize **SLDS Styling Hooks** over custom CSS.',
      '- Use **LDS 2** and **Lightning Data Service** whenever possible.',
      '- User feedback: Toasts with **Custom Labels**. Never hardcode strings.',
      '- **UX Gate (when generating LWC UI):** verify contrast (4.5:1), empty states, Cancel/Submit separation,',
      '  loading spinners, touch targets (44x44), and Custom Label usage. See `ux-standards.mdc` for full checklist.',
      '',
      '## Testing',
      '- **Deploy before testing (CRITICAL).** Never run a test class if the productive Apex class it covers',
      '  has not been deployed to the target sandbox yet. The sequence is always:',
      '  1. Deploy the modified productive class (`sf project deploy start`).',
      '  2. Wait for the deployment to succeed (monitor to completion).',
      '  3. Only then run the corresponding test class (`sf apex test run`).',
      '- If the user asks to run tests without deploying first, warn them and deploy before proceeding.',
      '- **Exactly one Assert per test method** using the modern `Assert` class.',
      '- Use `@TestSetup` for shared test data.',
      '- Use `System.runAs()` with Permission Set Group-based test users.',
      '- Wrap async Apex in `Test.startTest()` / `Test.stopTest()`.',
      '- Target **90% code coverage**.',
      '',
      '## Test Data Strategy',
      '- Use a centralized **TestDataFactory** class for all test data creation.',
      '- TestDataFactory must create records with all required fields populated — no partial inserts.',
      '- Map test users to **Permission Set Groups (PSGs)** — never assign Profiles directly in tests.',
      '- Use `System.runAs()` with PSG-based test users to validate field-level and object-level security.',
      '- For bulk tests: create N records (at minimum 200) to verify governor limit compliance.',
      '',
      '## Async Apex',
      '- No fixed pattern. When async need arises, discuss architecture with the developer.',
      '- Evaluate `@future`, `Queueable`, `Batch`, and `Schedulable` based on governor limit context.',
      '',
      '## Error Handling',
      '- Scan for existing logging framework before writing `try-catch`.',
      '- Never use `eslint-disable` or `@SuppressWarnings` as a first resort.',
      '- Triggers: `addError()` with Custom Labels. LWC: Toast notifications.',
      '',
      '## Flow Awareness',
      '- Avoid Mega-Flows. Recommend Sub-flows for modularity.',
      '- One Record-Triggered Flow per object/context (Before Save / After Save).',
      '- Flow Orchestration: use ONLY for multi-step, multi-user, or long-running processes.',
      '',
      '## Platform Events & Change Data Capture',
      '- Use Platform Events for loosely-coupled, event-driven integrations between Apex, Flows, and external systems.',
      '- Always define a replay ID strategy: subscribe with `-1` (tip) for real-time, or store the last replay ID for durable subscribers.',
      '- Use `EventBus.publish()` for Apex-initiated events. Handle `Database.SaveResult` to detect publish failures.',
      '- For Change Data Capture: subscribe to `/data/ChangeEvents` or object-specific channels. Process `ChangeEventHeader` to detect operation type.',
      '- Never use Platform Events for synchronous request-response patterns — they are fire-and-forget.',
      '',
      '## Invocable Actions (Flow-Apex Bridge)',
      '- Use `@InvocableMethod` to expose Apex logic to Flow builders. Keep the method signature simple.',
      '- Mark input/output variables with `@InvocableVariable` and always include `label` and `description`.',
      '- One invocable method per class. Name the class descriptively: `InvocableCreateCase`, `InvocableAssignTerritory`.',
      '- Bulkify: the `@InvocableMethod` receives `List<Request>` — process all records, never just the first.',
      '- Return `List<Result>` with meaningful output fields that Flow builders can reference downstream.',
      '',
      '## Custom Metadata Types',
      '- Use **CMDT** for app configuration that must be deployable (e.g., mapping tables, feature flags, thresholds).',
      '- Use **Custom Settings** only for org-level or user-level runtime toggles that change without deployment.',
      '- Use **Custom Labels** for translatable user-facing text, NOT for configuration values.',
      '- CMDT API Names: `<Feature>_Config__mdt`. Records: descriptive `DeveloperName`.',
      '- Always seed CMDT records in the deployment package — never rely on manual creation in target orgs.',
      '',
      ...documentationStandards(),
      '',
      ...deployment(),
      '',
      ...semanticCommits(),
      '',
      '## Sub-agent Handover',
      '- Pass to sub-agents: API version from `sfdx-project.json`, existing trigger handler pattern,',
      '  data layer strategy (JT_DynamicQueries vs DataSelector), and test user PSG names.',
      '- Sub-agents must follow: one Assert per test, zero logic in triggers.',
      '',
      ...interactionPreferences(),
    ].join('\n');
  },
};
