/*
 * Copyright 2026, Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const BT = '`';
const FENCE = BT.repeat(3);
const DS = '$';

export function diagramExportSkillMd(): string {
  return [
    '---',
    'name: diagram-export',
    'description: >-',
    '  Export Mermaid diagrams to external tools (Lucidchart, draw.io, Visio) or render',
    '  locally to SVG/PDF. Auto-detects available targets and falls back to local Mermaid',
    '  rendering when no external tool is configured. USE FOR: export diagram, push to lucid,',
    '  export to lucidchart, drawio export, draw.io, visio, diagram export, diagram sync,',
    '  render diagram, local diagram, mermaid to pdf, mermaid to svg. Reusable by BA, PM,',
    '  and Architect profiles.',
    '---',
    '',
    '# Diagram Export',
    '',
    '## Prerequisites',
    '',
    '| Tool | Check | Install |',
    '|------|-------|---------|',
    '| Node.js >= 18 | ' + BT + 'node --version' + BT + ' | [https://nodejs.org](https://nodejs.org) |',
    '| npx | ' + BT + 'npx --version' + BT + ' | Included with Node.js |',
    '| mermaid-to-drawio (optional) | ' +
      BT +
      'command -v mermaid-to-drawio' +
      BT +
      ' | ' +
      BT +
      'npm install -g mermaid-to-drawio' +
      BT +
      ' |',
    '| Lucid OAuth token (for lucid target) | ' +
      BT +
      'echo $LUCID_ACCESS_TOKEN' +
      BT +
      ' | See Lucidchart section below |',
    '',
    '> mermaid-cli is auto-downloaded via ' +
      BT +
      'npx -y' +
      BT +
      '. If mermaid-to-drawio is not installed, the script falls back to SVG wrapping.',
    '',
    '## Overview',
    '',
    "This skill exports Mermaid diagrams to the user's preferred diagramming tool.",
    'Before exporting, **always ask the user which target they want** unless they',
    'have already specified one.',
    '',
    '## Supported Targets',
    '',
    '| Target | Auth Required | Output |',
    '|--------|--------------|--------|',
    '| ' + BT + 'lucid' + BT + ' | Yes (OAuth 2.0) | Diagram created in Lucidchart |',
    '| ' + BT + 'drawio' + BT + ' | No | ' + BT + '.drawio' + BT + ' XML file (open in draw.io / diagrams.net) |',
    '| ' + BT + 'local' + BT + ' | No | SVG and/or PDF via ' + BT + 'mermaid-cli' + BT + ' |',
    '',
    '## Decision Flow',
    '',
    '1. Ask the user: **"Which diagramming tool do you want to export to?** (Lucidchart, draw.io, or local SVG/PDF)"',
    '2. Validate prerequisites for the chosen target.',
    '3. If prerequisites are missing, inform the user and offer ' + BT + 'local' + BT + ' as fallback.',
    '4. Execute the export.',
    '',
    '## Using the Helper Script',
    '',
    FENCE + 'bash',
    '# Auto-detect target (checks LUCID_ACCESS_TOKEN, falls back to drawio, then local)',
    'bash .setup-agents/skills/diagram-export/scripts/export-diagram.sh diagram.mmd',
    '',
    '# Explicit target',
    'bash .setup-agents/skills/diagram-export/scripts/export-diagram.sh diagram.mmd --target lucid --title "My Diagram"',
    'bash .setup-agents/skills/diagram-export/scripts/export-diagram.sh diagram.mmd --target drawio',
    'bash .setup-agents/skills/diagram-export/scripts/export-diagram.sh diagram.mmd --target local --format pdf',
    FENCE,
    '',
    '---',
    '',
    '## Target: Lucidchart',
    '',
    '### Prerequisites',
    '',
    'Lucidchart requires OAuth 2.0 Authorization Code Flow:',
    '',
    '1. Go to [Lucid Developer Portal](https://lucid.app/developer).',
    '2. Create an application and note the **Client ID** and **Client Secret**.',
    '3. Store credentials:',
    '',
    FENCE + 'bash',
    'export LUCID_CLIENT_ID="your-client-id"',
    'export LUCID_CLIENT_SECRET="your-client-secret"',
    'export LUCID_ACCESS_TOKEN="your-oauth-token"',
    FENCE,
    '',
    'To obtain an access token:',
    '',
    FENCE + 'bash',
    '# Step 1: Authorize (opens browser)',
    'open "https://lucid.app/oauth2/authorize?client_id=' +
      DS +
      '{LUCID_CLIENT_ID}&redirect_uri=http://localhost:3000/callback&response_type=code&scope=lucidchart.document.content"',
    '',
    '# Step 2: Exchange code for token',
    'curl -X POST https://api.lucid.co/oauth2/token \\',
    '  -d "grant_type=authorization_code" \\',
    '  -d "code=<AUTH_CODE>" \\',
    '  -d "client_id=' + DS + '{LUCID_CLIENT_ID}" \\',
    '  -d "client_secret=' + DS + '{LUCID_CLIENT_SECRET}" \\',
    '  -d "redirect_uri=http://localhost:3000/callback"',
    FENCE,
    '',
    '### How It Works',
    '',
    '1. Validates the Mermaid diagram.',
    '2. Converts to ' + BT + '.drawio' + BT + ' format (or SVG fallback).',
    '3. Pushes via ' + BT + 'POST https://api.lucid.co/documents' + BT + ' with the file.',
    '',
    '### Authentication Notes',
    '',
    '- Tokens expire. If the API returns 401, re-run the OAuth flow.',
    '- **Never commit tokens.** Use ' + BT + '.env' + BT + ' or secret managers.',
    '',
    '---',
    '',
    '## Target: draw.io',
    '',
    '### Prerequisites',
    '',
    'None. This target generates a ' + BT + '.drawio' + BT + ' XML file locally.',
    'Open it with [draw.io Desktop](https://www.drawio.com/) or [diagrams.net](https://app.diagrams.net).',
    '',
    '### How It Works',
    '',
    '1. Validates the Mermaid diagram.',
    '2. If ' + BT + 'mermaid-to-drawio' + BT + ' is installed, converts directly.',
    '3. Otherwise, renders to SVG and wraps it in a draw.io XML envelope.',
    '',
    FENCE + 'bash',
    '# Install converter (optional, improves fidelity)',
    'npm install -g mermaid-to-drawio',
    FENCE,
    '',
    '### draw.io XML Envelope (fallback)',
    '',
    'When ' + BT + 'mermaid-to-drawio' + BT + ' is unavailable, the script embeds the rendered SVG',
    'inside a draw.io-compatible XML wrapper so it can still be opened and edited.',
    '',
    '---',
    '',
    '## Target: Local (SVG / PDF)',
    '',
    '### Prerequisites',
    '',
    'Only ' + BT + 'npx' + BT + ' (always available with Node.js).',
    '',
    '### How It Works',
    '',
    '1. Validates the Mermaid diagram.',
    '2. Renders to SVG or PDF via ' + BT + 'mermaid-cli' + BT + '.',
    '3. For PDF: uses the story-mapping CSS to prevent truncation.',
    '',
    FENCE + 'bash',
    '# SVG output',
    'npx -y @mermaid-js/mermaid-cli mmdc -i diagram.mmd -o diagram.svg',
    '',
    '# PDF output (with custom CSS)',
    'bash .setup-agents/skills/story-mapping/scripts/render-pdf.sh diagram.mmd diagram.pdf',
    FENCE,
    '',
    '---',
    '',
    '## Supported Import Formats (Lucidchart)',
    '',
    '| Format | MIME Type |',
    '|--------|----------|',
    '| draw.io (.drawio) | ' + BT + 'x-application/vnd.lucid.drawio' + BT + ' |',
    '| Visio (.vsdx) | ' + BT + 'x-application/vnd.lucid.visio' + BT + ' |',
    '| Lucid native (.lucid) | ' + BT + 'x-application/vnd.lucid.standardImport' + BT + ' |',
    '',
  ].join('\n');
}

export function exportDiagramScript(): string {
  return [
    '#!/usr/bin/env bash',
    '# Exports a Mermaid diagram to Lucidchart, draw.io, or local SVG/PDF.',
    '#',
    '# Usage: export-diagram.sh <input.mmd> [--target lucid|drawio|local] [--title "Title"] [--format svg|pdf]',
    '# Auto-detection: LUCID_ACCESS_TOKEN set → lucid, else → drawio, else → local',
    'set -euo pipefail',
    '',
    '# ── Dependency guard ─────────────────────────────────────────────────────',
    'if ! command -v npx &>/dev/null; then',
    '  echo "ERROR: npx not found. Install Node.js >= 18 from https://nodejs.org"',
    '  exit 1',
    'fi',
    '',
    '# ── Parse arguments ──────────────────────────────────────────────────────',
    'INPUT=""',
    'TARGET=""',
    'TITLE=""',
    'FORMAT="svg"',
    '',
    'while [[ $# -gt 0 ]]; do',
    '  case "$1" in',
    '    --target) TARGET="$2"; shift 2 ;;',
    '    --title)  TITLE="$2"; shift 2 ;;',
    '    --format) FORMAT="$2"; shift 2 ;;',
    '    -*) echo "Unknown option: $1"; exit 1 ;;',
    '    *)  INPUT="$1"; shift ;;',
    '  esac',
    'done',
    '',
    'if [ -z "$INPUT" ]; then',
    '  echo "Usage: export-diagram.sh <input.mmd> [--target lucid|drawio|local] [--title \\"Title\\"] [--format svg|pdf]"',
    '  exit 1',
    'fi',
    '',
    'if [ ! -f "$INPUT" ]; then',
    '  echo "ERROR: Input file not found: $INPUT"',
    '  exit 1',
    'fi',
    '',
    '[ -z "$TITLE" ] && TITLE="$(basename "$INPUT" .mmd)"',
    '',
    '# ── Auto-detect target ───────────────────────────────────────────────────',
    'if [ -z "$TARGET" ]; then',
    '  if [ -n "${LUCID_ACCESS_TOKEN:-}" ]; then',
    '    TARGET="lucid"',
    '  elif command -v mermaid-to-drawio &>/dev/null; then',
    '    TARGET="drawio"',
    '  else',
    '    TARGET="local"',
    '  fi',
    '  echo "Auto-detected target: $TARGET"',
    'fi',
    '',
    '# ── Output validation helper ────────────────────────────────────────────',
    'ERROR_PATTERNS="No diagram detected|Syntax error in text|Parse error|UnknownDiagramError"',
    '',
    'validate_output() {',
    '  local file="$1"',
    '  if [ ! -f "$file" ]; then return 1; fi',
    '  local size',
    '  size=$(wc -c < "$file" | tr -d " ")',
    '  if [ "$size" -lt 512 ]; then',
    '    echo "WARN: Output file $file is suspiciously small (${size} bytes)."',
    '  fi',
    '  case "$file" in',
    '    *.svg)',
    '      if grep -qiE "$ERROR_PATTERNS" "$file" 2>/dev/null; then',
    '        echo "ERROR: $file contains error markers — diagram was not rendered."',
    '        return 1',
    '      fi ;;',
    '    *.pdf)',
    '      if command -v pdftotext &>/dev/null; then',
    '        local txt',
    '        txt=$(pdftotext "$file" - 2>/dev/null || true)',
    '        if echo "$txt" | grep -qiE "$ERROR_PATTERNS"; then',
    '          echo "ERROR: $file contains error text — diagram was not rendered."',
    '          return 1',
    '        fi',
    '      fi ;;',
    '  esac',
    '  return 0',
    '}',
    '',
    '# ── Validate Mermaid syntax ──────────────────────────────────────────────',
    'echo "Validating Mermaid diagram..."',
    'SVG_TMP="$(mktemp /tmp/mermaid-XXXXXX.svg)"',
    'LOG_TMP="$(mktemp /tmp/mmdc-XXXXXX.log)"',
    'npx -y @mermaid-js/mermaid-cli mmdc -i "$INPUT" -o "$SVG_TMP" 2>&1 | tee "$LOG_TMP"',
    'if grep -qiE "$ERROR_PATTERNS" "$LOG_TMP"; then',
    '  echo "ERROR: Invalid Mermaid syntax. Fix the diagram before exporting."',
    '  rm -f "$SVG_TMP" "$LOG_TMP"',
    '  exit 1',
    'fi',
    'if ! validate_output "$SVG_TMP"; then',
    '  echo "ERROR: Rendered SVG contains error markers. Fix Mermaid syntax in $INPUT."',
    '  rm -f "$SVG_TMP" "$LOG_TMP"',
    '  exit 1',
    'fi',
    '',
    '# ── Target: local ───────────────────────────────────────────────────────',
    'if [ "$TARGET" = "local" ]; then',
    '  OUTPUT="${INPUT%.mmd}.$FORMAT"',
    '  if [ "$FORMAT" = "pdf" ]; then',
    '    CSS_DIR="$(cd "$(dirname "$0")/.." && pwd)"',
    '    STORY_CSS="$(cd "$(dirname "$0")/../../story-mapping/assets" 2>/dev/null && pwd)/mermaid-pdf.css" || true',
    '    CSS_FLAG=""',
    '    [ -f "${STORY_CSS:-}" ] && CSS_FLAG="--cssFile $STORY_CSS"',
    '    # shellcheck disable=SC2086',
    '    npx -y @mermaid-js/mermaid-cli mmdc -i "$INPUT" -o "$OUTPUT" $CSS_FLAG --pdfFit',
    '  else',
    '    cp "$SVG_TMP" "$OUTPUT"',
    '  fi',
    '  rm -f "$SVG_TMP" "$LOG_TMP"',
    '  if ! validate_output "$OUTPUT"; then',
    '    echo "Check the Mermaid syntax in $INPUT."',
    '    rm -f "$OUTPUT"',
    '    exit 1',
    '  fi',
    '  echo "Exported to $OUTPUT"',
    '  exit 0',
    'fi',
    '',
    '# ── Target: drawio ──────────────────────────────────────────────────────',
    'DRAWIO_FILE="${INPUT%.mmd}.drawio"',
    '',
    'if [ "$TARGET" = "drawio" ] || [ "$TARGET" = "lucid" ]; then',
    '  if command -v mermaid-to-drawio &>/dev/null; then',
    '    echo "Converting to draw.io format..."',
    '    mermaid-to-drawio "$INPUT" -o "$DRAWIO_FILE"',
    '  else',
    '    echo "Wrapping SVG in draw.io XML envelope..."',
    '    SVG_CONTENT=$(cat "$SVG_TMP")',
    '    cat > "$DRAWIO_FILE" <<XMLEOF',
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<mxfile>',
    '  <diagram name="$TITLE">',
    '    <mxGraphModel>',
    '      <root>',
    '        <mxCell id="0"/>',
    '        <mxCell id="1" parent="0"/>',
    '        <mxCell id="2" value="" style="shape=image;image=data:image/svg+xml,${SVG_CONTENT}" vertex="1" parent="1">',
    '          <mxGeometry width="800" height="600" as="geometry"/>',
    '        </mxCell>',
    '      </root>',
    '    </mxGraphModel>',
    '  </diagram>',
    '</mxfile>',
    'XMLEOF',
    '  fi',
    'fi',
    '',
    'rm -f "$SVG_TMP" "$LOG_TMP"',
    '',
    '# ── If target is drawio, we are done ────────────────────────────────────',
    'if [ "$TARGET" = "drawio" ]; then',
    '  echo "Exported to $DRAWIO_FILE — open with draw.io or diagrams.net"',
    '  exit 0',
    'fi',
    '',
    '# ── Target: lucid ───────────────────────────────────────────────────────',
    'if [ -z "${LUCID_ACCESS_TOKEN:-}" ]; then',
    '  echo "ERROR: LUCID_ACCESS_TOKEN is not set."',
    '  echo "Falling back to draw.io export."',
    '  echo "Exported to $DRAWIO_FILE — open with draw.io or diagrams.net"',
    '  exit 0',
    'fi',
    '',
    'echo "Pushing to Lucidchart..."',
    'RESPONSE=$(curl -s -w "\\n%{http_code}" -X POST "https://api.lucid.co/documents" \\',
    '  -H "Authorization: Bearer ${LUCID_ACCESS_TOKEN}" \\',
    '  -H "Lucid-Api-Version: 1" \\',
    '  -F "title=${TITLE}" \\',
    '  -F "product=lucidchart" \\',
    '  -F "file=@${DRAWIO_FILE};type=x-application/vnd.lucid.drawio")',
    '',
    'HTTP_CODE=$(echo "$RESPONSE" | tail -1)',
    'BODY=$(echo "$RESPONSE" | sed \'$d\')',
    '',
    'if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then',
    '  echo "Document created successfully in Lucidchart."',
    '  echo "$BODY"',
    'elif [ "$HTTP_CODE" = "401" ]; then',
    '  echo "ERROR: Authentication failed (401). Token may be expired."',
    '  echo "Falling back to draw.io export."',
    '  echo "Exported to $DRAWIO_FILE — open with draw.io or diagrams.net"',
    'else',
    '  echo "ERROR: Lucid API returned HTTP $HTTP_CODE"',
    '  echo "$BODY"',
    '  exit 1',
    'fi',
    '',
  ].join('\n');
}
